---
version: "3.3"
services:
  thousandeyes:
    container_name: thousandeyes_cbr_lab
    environment:
      TEAGENT_ACCOUNT_TOKEN: m2ldqmq15xj42mwa9i498qtcwz157ro9
      TEAGENT_INET: 4
    volumes:
      - /mnt/docker/thousandeyes:/var/lib/te-agent
      - /mnt/docker/thousandeyes:/var/lib/te-browserbot
      - /mnt/docker/thousandeyes:/var/log/agent
    image: thousandeyes/enterprise-agent
    restart: always
